# Installs vscodium based on instructions at https://vscodium.com/

- name: Ensure vscodium is installed
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: vscodium GPG key is downloaded
      get_url:
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-vscodium
        owner: root
        group: root
        mode: 0644
        setype: cert_t
        backup: yes

    - name: vscodium GPG key is in RPM database
      rpm_key:
        state: present
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-vscodium

    - name: DNF repository for Fedora/RHEL is set up
      yum_repository:
        name: gitlab.com_paulcarroty_vscodium_repo
        description: vscodium.com repository for Fedora/RHEL
        baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-vscodium
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        file: vscodium
        state: present

    - name: codium package is installed
      package:
        name: codium
        state: present
